### ISSUE TITLE
Wrong calculation in inventory when adding an item

### ISSUE THREAD

**Issue by KoolieAid** [KoolieAid/CookingYnah#15]
Adds another element in the inventory instead of adding count

![image](https://github.com/KoolieAid/CookingYnah/assets/26061711/53e02b88-f00b-4705-9bb5-ee6b7d709454)

**Comment by AlexanderGregorSanchez** [comment]
The names are diferent(leek vs leak) and adding an item is based on the name of item

**Comment by KoolieAid** [comment]
lmao im just retarded then
