### ISSUE TITLE
MiniBoss Respawn

### ISSUE THREAD

**Issue by LauSnchzz** [KoolieAid/CookingYnah#16]
- Mini boss respawns spawns in base

Steps to reproduce:
- Go to dungeon 1
- Kill boss
- Immediately go back to base or enter the cave entrance/exit
- Mini boss appears

**Comment by LauSnchzz** [comment]
- basic enemies also spawn when done with same steps

**Comment by AlexanderGregorSanchez** [comment]
Did you check the main level hierarchy if there is also still the spawning stuff there

**Comment by AlexanderGregorSanchez** [comment]
The actual calling of the spawn function was started in a asyncCorutine so I guess it persisted through a scene change

**Comment by KoolieAid** [comment]
> The actual calling of the spawn function was started in a asyncCorutine so I guess it persisted through a scene change

async routines are actually handled by awaitercoroutiner thats persistent through a scene change, thats maybe why it didnt cancel a spawn
